package com.example.fixturepackaging

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class FixturePackagingApplicationTests(@Autowired private val testData: TestData) {

	@Test
	fun contextLoads() {
	}

	@Test
	fun testDataAccess() {
		assertEquals("generated by testData", testData.someTestData().field1)
	}

}
